package com.eventara.notification.entity;

public enum NotificationType {
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    TICKET_ISSUED,
    EVENT_CANCELLED,
    EVENT_POSTPONED,
    EVENT_APPROVED,
    EVENT_REJECTED,
    ORGANIZER_APPROVED,
    ORGANIZER_REJECTED,
    NEW_BOOKING_RECEIVED,
    NEW_ORGANIZER_APPLICATION,
    NEW_EVENT_SUBMISSION,
    GENERAL
}
